a = int(True)
print(type(a), a)
b = int(False)
print(type(b), b)
c = int(10.9)
print(type(c), c)
d = int("10")
print(type(d), d)
aa = float(10)
print(type(aa), aa)
bb = float(True)
print(type(bb), bb)
cc = float("10")
print(type(cc), cc)
aaa = str(True)
print(type(aaa), aaa)
bbb = str(10)
print(type(bbb), bbb)
ccc = str(10.34)
print(type(ccc), ccc)

aaaaa = chr(25105)
print(type(aaaaa), aaaaa)